name: Test on github

on:
  push:
    branches:    
      - main
      - dev
      - feature/*

  pull_request:
    branches:
      - main
      - dev
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
    
    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests with pytest
      run: |        
        uv run pytest

    - name: Lint with ruff
      run: |
        uv run ruff check

    - name: Check code with pyright
      run: |
        uv run pyright
